#!/bin/bash

set -e

mkdir -p coverage
cd coverage

[ -f CMakeCache.txt ] || cmake .. -DMYPROJ_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Coverage

make

lcov --directory . --zerocounters
lcov -c -i -d . -o coverage.base

LD_LIBRARY_PATH=$PWD/lib \
CTEST_OUTPUT_ON_FAILURE=1 \
ctest --timeout 180

find . \( -iname "*.gcda"  -or -iname "*.gcno" \) -exec chmod 664 '{}' \;

lcov --directory . --capture --output-file coverage.info
lcov -a coverage.base -a coverage.info --output-file coverage.total

lcov --remove coverage.total \
  '/usr/**' \
  '*tests/**' \
  '*gtest/**' \
  --output-file coverage.info.cleaned

genhtml --function-coverage -o report coverage.info.cleaned
